version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'monthly'
groups:
  production-dependencies:
    patterns:
      - 'production'
  development-dependencies:
    patterns:
      - 'development'
